name: deploy

on: [push] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - run: ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} "cd inventaire_projet_octobre && git pull"
      - run: ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} "cd inventaire_projet_octobre && docker compose up -d --build --force-recreate"