name: build

on: [push] 
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker compose up -d 
      - run: docker compose exec php php symfony doctrine:database:create --env=test
      - run: docker compose exec php php symfony console doctrine:schema:update --env=test --force
      - run: docker compose exec php composer install
      - run: docker compose exec php php bin/phpunit
     