name: build

on: [push] 
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker compose up -d 
      - run: ls -lah vendor/symfony/phpunit-bridge/bin/
      - run: docker compose exec php php bin/simple-phpunit
     